image: docker:18.09.7

variables:
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:18.09.7-dind

tests:
  before_script:
    - docker version
    - apk add docker-compose

  script:
    - ./compose-test.sh


