version: '3'

services:
  builder:
    build:
      context: .
      args:
        BUILD_ARGS: test
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./cmake-build-modules:/home/builder/bin
  environment:
    build: ./tests/environment
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./tests/environment/deathmatch:/home/mtasa/mods/deathmatch
      - ./cmake-build-modules:/home/mtasa/x64/modules

volumes:
  mtasa_modules: